### ISSUE TITLE
Send mqtt config without flashing

### ISSUE THREAD

**Issue by mtfurlan** [i3detroit/Automatic-IoT-module-programming#19]
If you flash a device, but it fails to reboot properly, there is no way to send the commands to it without reflashing.

**Comment by mkfink** [comment]
Would you want this as an argument in the flash script to skip flashing and only run commands, or a separate script?

**Comment by mtfurlan** [comment]
I think an argument, cause it's mostly the same.
`--skip-flashing` ?

**Comment by mkfink** [comment]
Yeah, that makes sense. And maybe we should rename the script, since we'd be running flash.py --skip-flashing

**Comment by mtfurlan** [comment]
flash.py -> configure.py
write_hass_config.py -> hass_config.py

With the hass config one I just never remember the name and auto completing hass doesn't work. Not super important.

**Comment by mkfink** [comment]
Could merge the hass_config script into the other one too

**Comment by mtfurlan** [comment]
--write-hass-config?

**Comment by mkfink** [comment]
https://github.com/i3detroit/Automatic-IoT-module-programming/pull/22
