### ISSUE TITLE
Check for duplicate and valid IPs

### ISSUE THREAD

**Issue by mkfink** [i3detroit/Automatic-IoT-module-programming#40]
Should check that multiple devices do not share the same valid IP and error out if so to prevent things from being flashed wrongly. I specify _vaild_ here as I tend to use placeholders like '192.168.1.x' when I'm flashing over serial and haven't set a device up on my network yet.

**Comment by abzman** [comment]
Maybe allow the same ip if they have different sites, me programming 192.168.1.132 for my house or marks would be ok, it just can't do both as a batch because they are on mutually exclusive networks.

**Comment by mkfink** [comment]
The time to check might then be after selecting devices in provision.py. Could also add at least a warning if you're trying to flash devices from multiple sites via wifi, since that's most likely going to fail

**Comment by mkfink** [comment]
I forgot the same IP/different site case, but I added a simple check for duplicate names and duplicate validish IPs ('\d+.\d+.\d+.\d+'). It doesn't error out, just prints a warning when you run provision.py.
